export const projectsList = [
  { id: 0,
    name: "Argent Bank",
    image: "/images/bank-tree.webp",
    github:"https://github.com/mowebiaz/ArgentBank",
    context: "Argent Bank est une application web de gestion de compte bancaire. Elle souhaite mettre en place un nouveau système d'authentification pour son application bancaire, et de nouvelles fonctionnalités pour le tableau de bord des utilisateurs.",
    works: ["Créer l’application web complète et responsive avec React", 
      "Afficher les données du back-end sur l'interface via des appels API",
      "Configurer des routes API pour la communication client / serveur",
      "Implémenter la gestion des données avec Redux "],
    technologies: ["React", "Redux", "API", "Swagger"]
  },
  { id: 1,
    name: "724Events",
    image: "/images/724events.webp",
    github:"https://github.com/mowebiaz/724events",
    context: "L'agence 724Events a commencé l’intégration de la nouvelle version de son site vitrine, mais le projet a été interrompu. Le site est presque fonctionnel, mais il subsiste quelques bugs qui entravent son bon usage par les visiteurs.",
    works: ["Résoudre les bugs", 
      "Rédiger le cahier de recettes", 
      "Ajouter les tests manquants: tests unitaires et tests fonctionnels"],
    technologies: ["React", "Jest" ]
  },
  { id: 2,
    name: "Nina Carducci",
    image: "/images/nina-carducci.webp",
    href: "https://mowebiaz.github.io/ninacarducci/",
    github:"https://github.com/mowebiaz/ninacarducci",
    context: "Le site de Nina Carducci, photographe professionnelle, est très long à charger, et il ne lui a encore jamais permis d’acquérir de nouveaux clients. ",
    works: ["Optimiser les performances", 
      "Optimiser l’accessibilité", 
      "Mettre en place le référencement local", 
      "Ajouter les meta pour les réseaux sociaux"],
    technologies: ["Lighthouse", "SEO"]
  },
  { id: 3,
    name: "Kasa",
    image: "/images/kasa.webp",
    github:"https://github.com/mowebiaz/kasa",
    context: "Kasa, entreprise de location d’appartements entre particuliers, s'est lancé dans la refonte totale de son site, avec React côté front-end.",
    works: ["Développer des éléments de l'interface grâce à des composants React",
      "Configurer la navigation entre les pages de l'application avec React Router",
      "Ajouter les animations CSS"],
    technologies: ["React", "SASS"]
  },
  {id:4,
    name: "Menu Maker by Qwenta",
    image: "/images/qwenta.webp",
    github:"",
    context: "Qwenta souhaite faire développer un “Menu Maker” : un site permettant aux restaurateurs d’afficher et de mettre en page leurs menus facilement, en quelques clics. ",
    works: ["Rédiger les spécifications techniques à partir des besoins fonctionnels",
      "Mettre en place une méthode de veille technologique",
      "Organiser la gestion de projet du développement du site"
    ],
    technologies: ["gestion de projet", "Wakelet", "Notion"]
  },
    { id: 5,
    name: "Sophie Bluel",
    image: "/images/sophie-bluel.webp",
    github:"https://github.com/mowebiaz/Portfolio-architecte-sophie-bluel",
    context: "Sophie Bluel, architecte d'intérieur, souhaite faire développer son site portfolio .",
    works: ["Développer la page de présentation des travaux, avec la possibilité de les filtrer par catégories", 
      "Développer la page de connexion de l'administrateur du site",
    "Développer la modale permettant d'uploader de nouveaux médias"],
    technologies: ["API", "Javascript"]
  }, 
  { id: 6,
    name: "Print It",
    image: "/images/colors.webp",
    href: "https://mowebiaz.github.io/PrintIt/",
    github:"https://github.com/mowebiaz/PrintIt",
    context: "Une petite imprimerie familiale, Print it, souhaite dynamiser son site Internet statique.",
    works: ["Créer le carrousel de la page d'accueil"],
    technologies: ["Javascript"]
  },
  { id: 7,
    name: "Ohmyfood",
    image: "/images/ohmyfood.webp",
    href: "https://mowebiaz.github.io/ohmyfood/index.html",
    github:"https://github.com/mowebiaz/ohmyfood",
    context: "Ohmyfood est une jeune startup sur le marché de la restauration. Elle souhaite développer un site “mobile first” qui répertorie les menus de restaurants gastronomiques. En plus des systèmes classiques de réservation, les clients pourront composer le menu de leur repas pour que les plats soient prêts à leur arrivée.",
    works: ["Développer le site en mobile-first à partir des maquettes", "Ajouter les animations"],
    technologies: ["SASS", "animations"]
  },
  { id: 8,
    name: "Booki",
    image: "/images/booki.webp",
    href: "",
    github:"",
    context: "Booki souhaite développer un site Internet qui permette aux usagers de trouver des hébergements et des activités dans la ville de leur choix",
    works: ["Intégrer la maquette en mobile-first"],
    technologies: ["HTML", "CSS"]
  }
]
