export const projectsList = [
  { id: 0,
    name: "Argent Bank",
    image: "/images/bank-tree.webp",
    github:"https://github.com/mowebiaz/ArgentBank",
    context: "Argent Bank est une application web de gestion de compte bancaire",
    works: ["optimisation", "debug", "jjjjjjjjj  jjjjjjjjjjjjjj  jjjjjjjjjjjjjjj  jjjjjjjjjjjjjjjjjjjjjjjjj   jjjjjjjjjjjjjjjjjjjjjjjj  jjjjjjjj   jjjjjjjjjjjjjjj   jjjjjjjjjjjjjj   jjjjjjjjjjjjjjjjj"],
    technologies: ["React", "Redux", "Tailwind CSS"]
  },
  { id: 1,
    name: "724Events",
    image: "/images/bank-tree.webp",
    github:"https://github.com/mowebiaz/ArgentBank",
    context: "Argent Bank est une application web de gestion de compte bancaire",
    works: ["optimisation", "debug"],
    technologies: ["React", "Redux", "Tailwind CSS"]
  },
  { id: 2,
    name: "Nina Carducci",
    image: "/images/bank-tree.webp",
    href: "hghgjg",
    github:"https://github.com/mowebiaz/ArgentBank",
    context: "Argent Bank est une application web de gestion de compte bancaire",
    works: ["optimisation", "debug"],
    technologies: ["React", "Redux", "Tailwind CSS"]
  },
  { id: 3,
    name: "Kasa",
    image: "/images/bank-tree.webp",
    href: "hgjgjhgj",
    github:"https://github.com/mowebiaz/ArgentBank",
    context: "Argent Bank est une application web de gestion de compte bancaire",
    works: ["optimisation", "debug"],
    technologies: ["React", "Redux", "Tailwind CSS"]
  },
  { id: 4,
    name: "Argent Bank",
    image: "/images/bank-tree.webp",
    href: "jhgjghjgh",
    github:"https://github.com/mowebiaz/ArgentBank",
    context: "Argent Bank est une application web de gestion de compte bancaire",
    works: ["optimisation", "debug"],
    technologies: ["React", "Redux", "Tailwind CSS"]
  },
  { id: 5,
    name: "Argent Bank",
    image: "/images/bank-tree.webp",
    href: "hgjgj",
    github:"https://github.com/mowebiaz/ArgentBank",
    context: "Argent Bank est une application web de gestion de compte bancaire",
    works: ["optimisation", "debug"],
    technologies: ["React", "Redux", "Tailwind CSS"]
  }, 
  { id: 6,
    name: "Argent Bank",
    image: "/images/bank-tree.webp",
    href: "ghghjghj",
    github:"https://github.com/mowebiaz/ArgentBank",
    context: "Argent Bank est une application web de gestion de compte bancaire",
    works: ["optimisation", "debug"],
    technologies: ["React", "Redux", "Tailwind CSS"]
  }
]