export const projectsList = [
  { id: 0,
    name: "Argent Bank",
    image: "/images/bank-tree.webp",
    github:"https://github.com/mowebiaz/ArgentBank",
    context: "Argent Bank est une application web de gestion de compte bancaire. Elle souhaite mettre en place un nouveau système d'authentification pour son application bancaire, et de nouvelles fonctionnalités pour le tableau de bord des utilisateurs.",
    works: ["Créer l’application web complète et responsive avec React", 
      "Intégrer les appel à l'API ", 
      "Utiliser Redux pour gérer les données de l’application",
      "Proposer les nouvelles routes possibles pour l’API et rédiger la documentation swagger"],
    technologies: ["React", "Redux", "swagger"]
  },
  { id: 1,
    name: "724Events",
    image: "/images/bank-tree.webp",
    github:"https://github.com/mowebiaz/724events",
    context: "L'agence 724Events a commencé l’intégration de la nouvelle version de son site vitrine, mais le projet a été interrompu. Le site est presque fonctionnel, mais il subsiste quelques bugs qui entravent son bon usage par les visiteurs.",
    works: ["Résoudre les bugs", "Rédiger le cahier de recettes", "Ajouter les tests manquants: tests unitaires et tests fonctionnels"],
    technologies: ["React", "Jest" ]
  },
  { id: 2,
    name: "Nina Carducci",
    image: "/images/nina-carducci.webp",
    href: "https://mowebiaz.github.io/ninacarducci/",
    github:"https://github.com/mowebiaz/ninacarducci",
    context: "klkjljlkjljljklj",
    works: ["Optimiser les persformances", "Optimiser l’accessibilité", "Mettre en place le référencement local", "Ajouter les meta pour les réseaux sociaux."],
    technologies: ["Lighthouse", ]
  },
  { id: 3,
    name: "Kasa",
    image: "/images/bank-tree.webp",
    href: "hgjgjhgj",
    github:"https://github.com/mowebiaz/ArgentBank",
    context: "Argent Bank est une application web de gestion de compte bancaire",
    works: ["optimisation", "debug"],
    technologies: ["React", "Redux"]
  },
  { id: 4,
    name: "Menu Maker by Qwenta",
    image: "/images/bank-tree.webp",
    href: "jhgjghjgh",
    github:"https://github.com/mowebiaz/ArgentBank",
    context: "Argent Bank est une application web de gestion de compte bancaire",
    works: ["optimisation", "debug"],
    technologies: ["Notion"]
  },
  { id: 5,
    name: "Sophie Bluel",
    image: "/images/sophie-bluel.png",
    href: "hgjgj",
    github:"https://github.com/mowebiaz/Portfolio-architecte-sophie-bluel",
    context: "Argent Bank est une application web de gestion de compte bancaire",
    works: ["optimisation", "debug"],
    technologies: ["React", "Redux"]
  }, 
  { id: 6,
    name: "PrintIt",
    image: "/images/colors.jpg",
    href: "https://mowebiaz.github.io/PrintIt/",
    github:"https://github.com/mowebiaz/PrintIt",
    context: "Argent Bank est une application web de gestion de compte bancaire",
    works: ["optimisation", "debug"],
    technologies: ["React", "Redux"]
  },
  { id: 7,
    name: "Ohmyfood",
    image: "/images/ohmyfood.jpg",
    href: "https://mowebiaz.github.io/PrintIt/",
    github:"https://github.com/mowebiaz/PrintIt",
    context: "Argent Bank est une application web de gestion de compte bancaire",
    works: ["optimisation", "debug"],
    technologies: ["Sass", "Redux"]
  },
  { id: 8,
    name: "Booki",
    image: "/images/ohmyfood.jpg",
    href: "https://mowebiaz.github.io/PrintIt/",
    github:"https://github.com/mowebiaz/PrintIt",
    context: "Argent Bank est une application web de gestion de compte bancaire",
    works: ["optimisation", "debug"],
    technologies: ["Sass", "Redux"]
  }
]