import "./styles/sass/globals.scss";
import { inter } from './styles/fonts';
import { Header } from './components/Header/Header';
import { Footer } from './components/Footer/Footer';

export const metadata = {
  title: "Morgane Web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
